Document: django-userlog
Title: Debian django-userlog Manual
Author: <insert document author here>
Abstract: This manual describes what django-userlog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/django-userlog/django-userlog.sgml.gz

Format: postscript
Files: /usr/share/doc/django-userlog/django-userlog.ps.gz

Format: text
Files: /usr/share/doc/django-userlog/django-userlog.text.gz

Format: HTML
Index: /usr/share/doc/django-userlog/html/index.html
Files: /usr/share/doc/django-userlog/html/*.html
